### ISSUE TITLE
CMAssetIntelligencePoint: Embedded instance DSC_CMAssetIntelligenceSynchronizationSchedule seems unnecessary

### ISSUE THREAD

**Issue by johlju** [dsccommunity/ConfigMgrCBDsc#23]
In the schema for the resource DSC_CMAssetIntelligencePoint there is an embedded instance class DSC_CMAssetIntelligenceSynchronizationSchedule that looks unnecessary. It looks like the properties in this class could be moved into the resource schema instead.
 
https://github.com/dsccommunity/ConfigMgrCBDsc/blob/fac77a0e87510c70ea90c35d8a77dc41afa47bd4/source/DSCResources/DSC_CMAssetIntelligencePoint/DSC_CMAssetIntelligencePoint.schema.mof#L15-L20

If the property `Schedule` would take an array of DSC_CMAssetIntelligenceSynchronizationSchedule I would understand the need for it, but now it looks like we could add two properties to the schema instead; `ScheduleRecurInterval` and `ScheduleRecurCount`.

**Comment by NEllis280** [comment]
When we issue a PR to fix this, we will need to ensure we are properly handling inputs that exceed the maximum allowed interval.
