### ISSUE TITLE
CMCollections: Embedded instance DSC_CMCollectionRefreshSchedule seems unnecessary

### ISSUE THREAD

**Issue by johlju** [dsccommunity/ConfigMgrCBDsc#25]
In the schema for the resource DSC_CMCollections there is an embedded instance class DSC_CMCollectionRefreshSchedule that looks unnecessary. It looks like the properties in this class could be moved into the resource schema instead.
 
https://github.com/dsccommunity/ConfigMgrCBDsc/blob/fac77a0e87510c70ea90c35d8a77dc41afa47bd4/source/DSCResources/DSC_CMCollections/DSC_CMCollections.schema.mof#L17-L22

If the property `RefreshSchedule` would take an array of DSC_CMCollectionRefreshSchedule I would understand the need for it, but now it looks like we could add two properties to the schema instead; `RefreshScheduleRecurInterval` and `RefreshScheduleRecurCount`.

**Comment by NEllis280** [comment]
When we issue a PR to fix this, we will need to ensure we are properly handling inputs that exceed the maximum allowed interval.

**Comment by NEllis280** [comment]
PR #78 Resolves this
