### ISSUE TITLE
CMForestDiscovery: Embedded instance DSC_CMForestDiscoveryPollingSchedule seems unnecessary

### ISSUE THREAD

**Issue by johlju** [dsccommunity/ConfigMgrCBDsc#27]
In the schema for the resource DSC_CMForestDiscovery there is an embedded instance class DSC_CMForestDiscoveryPollingSchedule that looks unnecessary. It looks like the properties in this class could be moved into the resource schema instead.
 
https://github.com/dsccommunity/ConfigMgrCBDsc/blob/fac77a0e87510c70ea90c35d8a77dc41afa47bd4/source/DSCResources/DSC_CMForestDiscovery/DSC_CMForestDiscovery.schema.mof#L11-L16

If the property `PollingSchedule` would take an array of DSC_CMForestDiscoveryPollingSchedule I would understand the need for it, but now it looks like we could add two properties to the schema instead; `PollingScheduleRecurInterval` and `PollingScheduleRecurCount`.

**Comment by NEllis280** [comment]
When we issue a PR to fix this, we will need to ensure we are properly handling inputs that exceed the maximum allowed interval.

**Comment by jeffotterpohl** [comment]
Updates to remove PollingSchedule (CimInstance) and max allowed interval for ScheduleCount are in PR.
