### ISSUE TITLE
CMIniFile: Is the resource IniSettingsFile an alternative

### ISSUE THREAD

**Issue by johlju** [dsccommunity/ConfigMgrCBDsc#28]
I suggest looking in if the resource IniSettingsFile in the FileContentDsc resource is an alternative to this resource. 
See documentation here: https://github.com/dsccommunity/FileContentDsc/wiki/IniSettingsFile

There might be a design choice to have a dedicated resource for modifying an ini file, then this is not relevant. 🙂

**Comment by rchristman89** [comment]
@johlju Didn't notice that resource. We could utilize that resource. With the CMIniFile it has the specifics that are need for the SCCM install. I like seeing all the options but I could see both ways.

**Comment by johlju** [comment]
You might be able to wrap the  IniSettingsFile in a composite resource in which you can have the parameters? 🤔

**Comment by johlju** [comment]
I'm not familiar with the SCCM ini file so I can't say my suggesting is a good option. You decide. 😄

**Comment by rchristman89** [comment]
@jeffotterpohl and @NEllis280  what are your thoughts. I could change that into a composite the only con I can think of is another module that would be needed.

**Comment by rchristman89** [comment]
Going to close this since this module is getting updated and is then included in the module.
