### ISSUE TITLE
CMCollections: Feature Direct membership using names

### ISSUE THREAD

**Issue by jeffotterpohl** [dsccommunity/ConfigMgrCBDsc#3]
Currently direct membership will only allow the use of ResourceIDs for input in the string array :
DirectMembership       = @('2063597577','2063597582')
desired state would be:
DirectMembership  = @('Computer1','Computer2')

Feature improvement would be to allow the use of names vs ResourceIds.

**Comment by NEllis280** [comment]
PR #78 resolves this
