### ISSUE TITLE
Update description, website, or topics of the repo

### ISSUE THREAD

**Issue by kilasuit** [dsccommunity/ConfigMgrCBDsc#35]
Whilst the readme is great, adding a simple description is useful when navigating round repositories like this, negating the need to scroll to the Readme.

**Comment by rchristman89** [comment]
@kilasuit Are you talking about a description in the PSD1 so it shows up in the PowerShell Gallery?

**Comment by kilasuit** [comment]
No I was meaning this area as it was blank before

![image](https://user-images.githubusercontent.com/6355225/84161306-0c200580-aa67-11ea-9aa7-c031db8fa38c.png)
