### ISSUE TITLE
CMHeartbeatDiscovery: ScheduleCount has restrictions depending on Days or Hours Interval

### ISSUE THREAD

**Issue by rchristman89** [dsccommunity/ConfigMgrCBDsc#39]
#### Details of the scenario you tried and the problem that is occurring
Setting ScheduleCount to anything over 31 and ScheduleInterval to Days results in it setting it to 31. 
Setting ScheduleCount to anything over 23 and ScheduleInterval to hours results in it setting it to 23.

**Comment by NEllis280** [comment]
Suggestion is to add write-warning for user friendliness. Do both in test and set.
