### ISSUE TITLE
CMCollections: ExcludeMembership import duplicate names in Rules

### ISSUE THREAD

**Issue by jeffotterpohl** [dsccommunity/ConfigMgrCBDsc#4]
with importing exclude membership rules, if a query rule already on the collection, has the same name as collection name being added to the exclude, the resource will silently continue but never add the exclude membership rule.

SmsProviderObjectPath : SMS_CollectionRuleQuery
RuleName              : Test2

Trying to add an exclude with collection name of Test2, it will silently fail and not do the exclude membership update.

**Comment by NEllis280** [comment]
PR #78 Resolves this
